### ISSUE TITLE
hide peers without endpoint to enable routing via other wireguard host

### ISSUE THREAD

**Issue by Miroka96** [githubixx/ansible-role-wireguard#101]
Hi!

In my current setup I use wireguard to manage very different hosts. Some are globally reachable servers, but most devices are behind firewalls. I need the possibility to access all devices from my own 'management' laptop, which is itself a device without global endpoint. Therefore, I have one dedicated wireguard server that serves as router between all NAT-ted devices. This 'router' has my whole IP range assigned as AllowedIPs. However, the routing does not work if the NAT-ted devices are set as peers without endpoints, because then routing requests (using ping) fail with `ping: sendmsg: Destination address required`.

Furthermore, devices without an endpoint also don't need to have a ListenPort as this port will never be used.

I suggest:
* to hide ListenPort, if the Endpoint is empty
* to hide the whole Peer section for devices whose Endpoint is empty

Best regards,
Miroka

**Comment by githubixx** [comment]
Should be fixed with https://github.com/githubixx/ansible-role-wireguard/pull/213
