### ISSUE TITLE
More robust error handling

### ISSUE THREAD

**Issue by gdanov** [githubixx/ansible-role-wireguard#125]
I like this role and use it to manage 20+ nodes mesh. 
The main issue I have is that if one node fails for whatever reason, it's excluded from the configuration and when the rest of the nodes are updated, they don't contain the key & IP of the failed node. This causes the node to be excluded and lose connectivity.

Most of the times I've hit this problem, a node had some silly minor issue I wasn't aware of (last example, expired cert for extra apt source) and unless I'm watching the script run, ready to cancel it, it ruins well-running node.

I'd like to see option where the play run is cancelled on the first error from a node.

**Comment by githubixx** [comment]
Have you tried using setting `ANSIBLE_ANY_ERRORS_FATAL=true` already? Maybe this helps in your case. See https://docs.ansible.com/ansible/latest/reference_appendices/config.html#any-errors-fatal for further information.

**Comment by gdanov** [comment]
Lol, no :) thanks for the hint.
