### ISSUE TITLE
wireguard_ip switch to netfilter

### ISSUE THREAD

**Issue by 927589452** [githubixx/ansible-role-wireguard#14]
It would be a good idea to switch the .split(/) statement to a netfilter statement

**Comment by githubixx** [comment]
Can you explain your statement with a simple example maybe a little bit?

**Comment by 927589452** [comment]
for example users could use the /32 or /255.255.255.255, whatever is easier for them and you have a small syntax check included
a later option would be to set a wireguard_ip_range var and pick unique random ips from the range per host leading to an easier setup for big environments

**Comment by githubixx** [comment]
Thanks for clarification. TBH the CIDR notation seems to be good enough for now. But a format check of the IP value may makes sense.
Something like `wireguard_ip_range` may makes sense for bigger setups but I'm not sure if this is a good idea. I haven't thought too much about the idea but I guess you then need some kind of a "state file" to have a mapping between the IP and the hostname. That's something that Kubernetes or Docker swarm does if you start a new pod or container and it gets an IP from a predefined range assigned when its started. I guess there a different approaches to solve this outside of this role. Maybe by using an host inventory plugin or creating a script that populates and configures the files in `hosts_vars/` accordingly. That should be only a few lines of Python or Bash code or whatever you prefer. I suspect that there are some more possibilities.
Honestly I don't really have the time to implement such features ATM in general or update the README with describes a possible procedure how to handle this. But pull requests of course welcome if they make sense. But as already mentioned this `wireguard_ip_range` thingy seems to be nothing that should be implemented in this role directly IMHO.
