### ISSUE TITLE
Routes not updating during re-configuration

### ISSUE THREAD

**Issue by lmm-git** [githubixx/ansible-role-wireguard#147]
When an existing Wireguard interface gets updated, on newer system [wg syncconf gets used](https://github.com/githubixx/ansible-role-wireguard/blob/c4a5677f723fb8ea3224e5753b9433498725d42f/handlers/main.yml).

The issue with `wg syncconf` seems to be that it [does not update routes](https://www.reddit.com/r/WireGuard/comments/s5cji1/wg_setconf_synccong_and_ip_routes/). In our case, we modified the routes of an existing Wireguard link, which led to the case that the wireguard handshakes were successfully sent and received, but we weren't able to transmit any data due to the missing routes.

Restarting the interfaces manually, solved the issue.

Maybe it would be nice to document this behavior and use the "old" restart mechanism by default as this issue can be quite hard to detect and debug.

**Comment by githubixx** [comment]
It's pretty unlikely that I'll go back to the old restart behavior. But maybe it makes sense to introduce a variable like `wireguard_interface_restart_behavior` (a little bit long name but came into mind at first :wink:). That one could've values like `restart` and `sync`. Then the user can decide what WireGuard interface restart behavior she/he prefers. Maybe even `none` makes sense in case someone wants to restart interfaces manually.

I also was thinking about `(pre|post)-hooks` for quite some time. They could be executed at the very beginning of the playbook and/or as one of the last tasks before the role finishes. Then someone can just put some custom tasks into some directory and the files in that directory will be executed in alphabetic order. But that's a more general purpose solution.

**Comment by githubixx** [comment]
I've implemented it a little bit differently in https://github.com/githubixx/ansible-role-wireguard/pull/156. So closing this one.
