### ISSUE TITLE
elementary OS support

### ISSUE THREAD

**Issue by NN708** [githubixx/ansible-role-wireguard#170]
[elementary OS](https://elementary.io/) is based on Ubuntu (Ubuntu 20.04 as for elementary OS 6), but has different Ansible facts:

```json
{
  "ansible_distribution": "elementary OS",
  "ansible_distribution_major_version": "6",
  "ansible_os_family": "elementary OS"
}
```

Hope this could be supported.

**Comment by githubixx** [comment]
Sadly there is no Vagrant Box available for elementary OS: https://app.vagrantup.com/boxes/search?provider=libvirt&q=elementary&sort=downloads&utf8=%E2%9C%93 That makes testing and implementation not really easy. But if it's based on Ubuntu 20.04 LTS this branch might work for you: https://github.com/githubixx/ansible-role-wireguard/tree/support-elementary-os Let me know if it works for you.

**Comment by githubixx** [comment]
Implemented in https://github.com/githubixx/ansible-role-wireguard/pull/171
