### ISSUE TITLE
Override port in `endpoint`

### ISSUE THREAD

**Issue by NN708** [githubixx/ansible-role-wireguard#172]
In [wg.conf.j2#L70](https://github.com/githubixx/ansible-role-wireguard/blob/master/templates/etc/wireguard/wg.conf.j2#L70) the host `port` is used in the `endpoint`. But sometimes these ports may be different (for example, the host is behind port forwarding). Is there a way to override the port in `endpoint`?

**Comment by githubixx** [comment]
You can define `wireguard_port` per host e.g. https://github.com/githubixx/ansible-role-wireguard/blob/master/molecule/kvm/molecule.yml#L284 . Is that's what you're searching for?

**Comment by NN708** [comment]
Thanks for your reply! I think that defining `wireguard_port` will generate configuration like this:
```
Port = 51821
Endpoint = 192.168.10.100:51821
```
But when the host is behind port forwarding, what we need is:
```
Port = 51820
Endpoint = 192.168.10.100:51821
```

**Comment by githubixx** [comment]
I guess this use case isn't currently implemented. But maybe the (undocumented) `wireguard_dc` variable might help. I explained the usage a little bit here: https://github.com/githubixx/ansible-role-wireguard/issues/167#issuecomment-1315847880
