### ISSUE TITLE
Need for storing state locally?

### ISSUE THREAD

**Issue by pierreozoux** [githubixx/ansible-role-wireguard#18]
Hi,

thanks for writing and sharing this role, this is really nice!

I have a question, is it necessary to store the state locally?
It would be easy to check if the server is already configured, find the private key and derive the public key, and if not, create the private key?

Am I missing something?

If you agree that storing the state is not so necessary, I can PR, to remove this need.

Cheers!

**Comment by githubixx** [comment]
Hi! Well, while I was developing the role I needed a way to have all keys at hand for creating all the WireGuard config files for every host. Having a variable for every key was quite handy. I also wanted to avoid to generate the public key files with every run of the role. But yeah, storing a local state is in general not the perfect way. So getting rid of this would be of course a nice thing and it should be doable. 

But one important thing here is to provide a upgrade path for already existing deployments. That would basically mean that the WireGuard configuration file for every host would be the single source of truth for a host's WireGuard private key. The bad thing in that case would be that you basically need to parse the configuration file with every run if the private key file isn't stored in a separate file. Of course it would be possible to create a file with the private key if it don't exist and derive the public key from it. That would avoid parsing the the configuration file. But maybe there are other options.

So if you provide a suitable PR that removes the need for the local state that would be fine :smiley:

**Comment by githubixx** [comment]
Fixed by https://github.com/githubixx/ansible-role-wireguard/pull/29
