### ISSUE TITLE
Split the main task

### ISSUE THREAD

**Issue by pierreozoux** [githubixx/ansible-role-wireguard#24]
I'm tempted to split the main task into various smaller chunks that would be more readable, would it be ok for you?

**Comment by githubixx** [comment]
Is the main task really that big? But if you want to make smaller chunks go ahead if it makes sense.

**Comment by pierreozoux** [comment]
Cool, I'll just wait you to merge some PR, and then I'll do that ;)

**Comment by githubixx** [comment]
No longer needed because of https://github.com/githubixx/ansible-role-wireguard/pull/29
