### ISSUE TITLE
Loop over all hosts from the play

### ISSUE THREAD

**Issue by pierreozoux** [githubixx/ansible-role-wireguard#26]
There is one more thing I'm not a fan.

https://github.com/githubixx/ansible-role-wireguard/blob/master/templates/wg.conf.j2#L19

I think the role should be agnostic of the groups the role user is using.

I think it would be better to use [ansible_play_hosts](https://docs.ansible.com/ansible/latest/reference_appendices/special_variables.html) and in your playbook, you tell the role to only use the vpn group. Basically it is the responsibility of the playbook to decide which hosts, and not the role.

If you agree, I'll refactor that part too.

**Comment by githubixx** [comment]
Yeah, I was never happy with that too. Makes sense to refactor.

**Comment by githubixx** [comment]
Implemented by https://github.com/githubixx/ansible-role-wireguard/pull/29
