### ISSUE TITLE
certs own by root

### ISSUE THREAD

**Issue by eleaner** [githubixx/ansible-role-wireguard#3]
Hi

I am running the role from ubuntu 16.04 to a bunch of ubuntu 16.04 machines
The role fails on TASK [ansible-role-wireguard : Read private key]
with messages like 
"Unable to find '/home/kisiel/wireguard/certs/hcloud1.vpn.private.key' in expected paths (use -vvvvv to see paths)"

"kisiel" is the user running ansible
the problem is that the /home/kisiel/wireguard/ was created with ownership to root
is this an error?

**Comment by githubixx** [comment]
If you set the variables `wireguard_cert_owner`and `wireguard_cert_group` accordingly the directory  permissions should be correct. By default their values are `root`.

**Comment by eleaner** [comment]
Thank you,

does it mean that ideally, I should be running this role as a root?
with your suggestion int went further but got stuck again on

FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable:
'ansible.vars.hostvars.HostVarsVars object' has no attribute 'public_key'"}

could it be related?

**Comment by githubixx** [comment]
>> does it mean that ideally, I should be running this role as a root?

Well kind of maybe. You can add something like this e.g.
```
ansible_connection: local
ansible_become_user: root
ansible_become: true
ansible_become_method: sudo
```
I use this settings for my workstation where I execute `ansible-playbook` command and I placed the settings in `host_vars/workstation` (while `workstation` of course needs to be replaced with the hostname where you want the settings to become active.

>>'ansible.vars.hostvars.HostVarsVars object' has no attribute 'public_key'"}

I'm not sure which task is causing this error (you only pasted the error message but not the task ;-) ). But do you have a Ansible `hosts` file with a `vpn` group? E.g.

```
[vpn]
hostname1
hostname2
```
Without this group the task which creates the WireGuard config file `wg.conf` will fail. But on the other hand without this group the playbook should have failed way earlier already.

**Comment by eleaner** [comment]
Oh, my bad
I do't know where the task info went
here it is
TASK [ansible-role-wireguard : Generate WireGuard configuration file]

It all went OK after change to "ansible_become_user: root"

Thank you so much
