### ISSUE TITLE
AnsibleUndefinedVariable: HostVarsVars object has no attribute 'public_key'

### ISSUE THREAD

**Issue by fourbytes** [githubixx/ansible-role-wireguard#39]
Quite new to Ansible, trying to get wireguard setup between a number of machines but am getting an error as below (let me know if you need the entire log). Is there a step I'm missing here, there doesn't seem to be anything in the readme about setting public keys, and if I understand it correctly, set public key fact should set this attribute.

```
TASK [wireguard : Set public key fact] ***************************************************************************************************
ok: [1.1.1.1]
ok: [2.2.2.2]
ok: [3.3.3.3]

TASK [wireguard : Create WireGuard configuration directory] ******************************************************************************
ok: [1.1.1.1]
ok: [2.2.2.2]
ok: [3.3.3.3]

TASK [wireguard : Generate WireGuard configuration file] *********************************************************************************
fatal: [1.1.1.1]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'public_key'"}
fatal: [2.2.2.2]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'public_key'"}
fatal: [3.3.3.3]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'ansible.vars.hostvars.HostVarsVars object' has no attribute 'public_key'"}
```

**Comment by githubixx** [comment]
Public key doesn't needs to be set. It's derived from the private key (either from the Wireguard config file if that one already exists or from a newly created private key). Generating keys happens automatically.

TBH I've currently no idea why this error occurs. I tried the current state of the role with a fresh host and it worked fine.

Which version of the role do you use?

I would suggest running `ansible-playbook -v ...` (add more `v` to get even more verbose logs). During `TASK [wireguard : Derive WireGuard public key]` you should see something like this:
```
ok: [hostname] => {"changed": false, "cmd": "echo 'aJbtNRapsFDa8zuA6pAz2mIJaPK1h6BQaNLKWAfOdV0=' | wg pubkey", ...
````
This is the part which derives the public key from the private key. In the next task `TASK [wireguard : Set public key fact]` you should see something like this:
```
ok: [hostname] => {"ansible_facts": {"public_key": "kwC/x6wHvBL2bUq6G4kvKZ3AjLRzbqmvf6bbHhzraD4="}, "changed": false}
```
This verifies that the private and public key at least exists.

**Comment by githubixx** [comment]
@fourbytes Can this issue be closed?
