### ISSUE TITLE
No support for roaming peers

### ISSUE THREAD

**Issue by matutter** [githubixx/ansible-role-wireguard#45]
There is no support for roaming peers because every node expects every-other peer to have a resolvable endpoint. Roaming peers (like a laptop) will never have resolvable endpoints so there must be a way to omit them from being present in other peer configs.

The issue comes from the config file template around this part.

```jinja2
{% for host in ansible_play_hosts %}
  {% if host != inventory_hostname %}
  
    [Peer]
```

Suggest adding a new variable `wireguard_roaming` to omit peers that are roaming.

```jinja2
{% for host in ansible_play_hosts %}
  {% if host != inventory_hostname %}
  
    [Peer]
    ...
    {% if hostvars[host].wireguard_roaming is undefined or not hostvars[host].wireguard_roaming %}
    ...
    {% endif %}
  {% endif %}
{% endfor %}
```

**Comment by githubixx** [comment]
I guess this PR https://github.com/githubixx/ansible-role-wireguard/pull/41 would solve your issue, right?

**Comment by camelstrike** [comment]
> I guess this PR #41 would solve your issue, right?

Would this work if I want to have a central "server" and groups of hosts which I want to connect to server but not see other hosts in specific groups?

**Comment by joneskoo** [comment]
@camelstrike Check out my #63 - I think that should work as it's possible to configure arbitrary peers to arbitrary nodes (by host vars or group vars depending on what you need). If you mean you don't want each node you configure to have each other as peer, then I guess you'd deploy multiple instances of this role, e.g. as independent playbooks to avoid them from being configured as each others' peer.

@matutter does #63 address your original need? I don't understand what you mean in the description.

**Comment by bastiencyr** [comment]
Hello @githubixx ,
Sorry to write a comment on a closed issue but it's related and I'm not sure the issue solves my problem.

I want to have the following configurations:
server: wg0.conf
```
[Interface]
Address = 10.8.0.1/24
PrivateKey = *************
ListenPort = 51820

[Peer]
PublicKey = public_key_client1
AllowedIPs = 10.8.0.2/32

[Peer]
PublicKey = public_key_client2
AllowedIPs = 10.8.0.3/32
```

Client1.wg0.conf
```
[Interface]
Address = 10.8.0.2/24
PrivateKey = *************

[Peer]
PublicKey = public_key_server
AllowedIPs = 10.8.0.0/24
Endpoint = server:51820
```

Client2.wg0.conf
```
[Interface]
Address = 10.8.0.3/24
PrivateKey = *************

[Peer]
PublicKey = public_key_server
AllowedIPs = 10.8.0.0/24
Endpoint = server:51820
```

So, the clients must go through the vpn server to communicate between each other.  Is that possible ?

**Comment by githubixx** [comment]
@bastiencyr Well, that's actually hard to say. If the clients don't have a public IP how should they communicate besides within an internal network? :wink: Maybe you mean that the clients are connected to the internet by using some internet provider and the server is some VPS/cloud server which has a public IP. That should work theoretically. In general by default Wireguard connections are bi-directional. So if client to server connection works the other way round also works. If all clients and the server are on the same Wireguard subnet like `10.8.0.0/24` then they normally know how to "find" each other. So should be possible to connect to a service on `client1` from `client2` via `server`. But I don't know your environment. Sometimes people have very strange setups :wink:
