### ISSUE TITLE
Switch to ELRepo for RHEL/Centos

### ISSUE THREAD

**Issue by elcomtik** [githubixx/ansible-role-wireguard#50]
I'm using this role to install wireguard on Centos7/8 systems. In recent update to Centos 7.8 wireguard caused problems(kernel panic at boot).  It updated kernel, however wireguard kernel module wasn't updated.

I troubleshooted issue and found that this role installed dkms-wireguard package from jdoss repository, which seems to be not maintained properly. I found that official wireguard webpage recommends to use ELRepo and kmod-wireguard package https://www.wireguard.com/install/. I manually switched to this repository and it worked perfectly. Extra bonus for getting rid of dependencies for building dkms.

We should also add some task to properly uninstall old repository and dkms package.

I would make PR if you would like.

**Comment by githubixx** [comment]
That would be great if you could submit a PR. The initial PR for CentOS support was created by a contributor as I don't use that distribution. The PR was LGTM at that time.
