### ISSUE TITLE
Generate static conf [no connect hosts]

### ISSUE THREAD

**Issue by groverz** [githubixx/ansible-role-wireguard#60]
Can you tell me if it is possible to generate keys and put them in a file without connecting via ssh? I have routers that require a specific setup.

**Original[ru]**
Подскажите можно ли сгенерировать ключи и положить их в файл не подключаясь по ssh. У меня есть роутеры  которым требуется специфичная установка.

**Comment by githubixx** [comment]
Currently it's not supported. There is a PR open that may solve your problem: https://github.com/githubixx/ansible-role-wireguard/pull/41 I'm just not sure if this would really work if there isn't any other host beside un-managed hosts. Never tried that. But please be aware that I won't merge that PR. So you might need to fork this repository and merge that PR on top of it.

**Comment by groverz** [comment]
Ok. Support ubiquti[OpenWrt/LEDE]? My [edgerouter](https://github.com/WireGuard/wireguard-vyatta-ubnt).
If you can make support, I am ready to offer a job? My router will be the only one in the local area connected to the wg network.

I copy local mashine config to edgerouter :). it’s not beautiful.
