### ISSUE TITLE
Machine readable copyright and license information, reuse.software

### ISSUE THREAD

**Issue by ypid** [githubixx/ansible-role-wireguard#71]
Hi, what do you think of https://reuse.software/ ?

**Comment by githubixx** [comment]
I don't want to put too much effort on licensing. I definitely won't sue somebody for forking this role and change it to meet their needs. As long as the changes are released as open source again I'm fine.

**Comment by ypid** [comment]
reuse.software is DebOps standard. Would you be open to a PR which makes this role compliant with it by having the copyright info reversed from the Git history?
