### ISSUE TITLE
Use no_log for tasks that might output sensitive information in --diff mode

### ISSUE THREAD

**Issue by ypid** [githubixx/ansible-role-wireguard#81]
https://docs.ansible.com/ansible/latest/reference_appendices/logging.html#protecting-sensitive-data-with-no-log

From discussion in #78. Tracked here separately.
Fixed in: https://github.com/ypid/ansible-wireguard/tree/prepare-for-debops

**Comment by githubixx** [comment]
I guess introducing the `no_log: True` attribute isn't that invasive if it's added to some tasks. But honestly it's not really the task of this role to protect people from shipping log output/secrets to a central logging system e.g. I guess people with strong requirements in this regards already have adjusted a fork of this role accordingly and will use `ansible-vault`, Ansible Tower or something like that.

**Comment by ypid** [comment]
I thought you support the GDPR. "Privacy by default" :)

> I guess

You know how it is. People pull down your role, go like: "oh look, it works". A year later, it runs as part of their site playbook. Someone comes and wants to detect config drift, another departments sets up Elastic for logging. By the time they all forgot that this role might output sensitive data to the Elastic to which others might have access to.

Our IT is to complex to take guesses. We need strong foundations.
