### ISSUE TITLE
Debian role fails (ansible_lsb)

### ISSUE THREAD

**Issue by djarbz** [githubixx/ansible-role-wireguard#86]
Role fails to execute on my Debian hosts due to ansible_lsb being empty.

Is there a better way to detect Raspbian or maybe have a check to see if ansible_lsb is populated?
The host in question is running Buster and all LSB named packages are installed, lsb-base & lsb-release.

```
[ansible]$ ansible node1 -m setup -a 'filter=ansible_lsb'
node1 | SUCCESS => {
    "ansible_facts": {
        "ansible_lsb": {},
        "discovered_interpreter_python": "/usr/bin/python"
    },
    "changed": false
}
```

**Comment by djarbz** [comment]
I don't have a Rpi handy to check what GatherFacts reports, but perhaps you could do a check on this file?

```
rpi44~# cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
rpi44~# uname -a
Linux rpi44 4.19.118-v7l+ #1311 SMP Mon Apr 27 14:26:42 BST 2020 armv7l GNU/Linux
```

**Comment by githubixx** [comment]
I'm sorry but I don't have any information about Raspbian. This code was contributed by @penguineer . I don't own a Raspberry. Maybe @penguineer might be able to help. 
I found an older Ansible issue that was never closed that seems to match your problem: https://github.com/ansible/ansible/issues/19874 Maybe the solution mentioned in this comment https://github.com/ansible/ansible/issues/19874#issuecomment-436542563 is a possible workaround for you.

**Comment by penguineer** [comment]
I will have a look.

For me the role works in both Debian buster and for RaspberryPi. (In fact I call ansible from Debian Buster to put Debian Buster machines and RaspberryPi machines into one wrieguard VPN.)

**Comment by penguineer** [comment]
@djarbz: You may assign  the issue to me, if possible. 

I might take a few days, though.

**Comment by djarbz** [comment]
@githubixx, I'll look at that other issue. I don't think I ran across that one in my search.
Also, I don't think I'm able to assign @penguineer to the issue, I think that is something that you need to do.

**Comment by djarbz** [comment]
If it helps, the host is actually Proxmox's Debian.

**Comment by penguineer** [comment]
> If it helps, the host is actually Proxmox's Debian.

Proxmox is just a virtualization suite, isn't it? Do they ship their own Debian derivate?

**Comment by djarbz** [comment]
They sure do, you can either use their provided iso or install ontop of an existing Debian.
In this case I used their iso.

**Comment by githubixx** [comment]
@djarbz Is this issue still relevant or could you possibly solve it with https://github.com/ansible/ansible/issues/19874#issuecomment-436542563 ?

**Comment by djarbz** [comment]
I think I had a corruption on my Proxmox instance.
I just verified that the setup module reports back the proper distribution on a new Proxmox host I have deployed.
But it does look, per that issue, that it has happened to others as well.

**Comment by penguineer** [comment]
Can and should that be fixed here or is it rather a Proxmox issue that has been uncovered and needs to be addressed elsewhere?

**Comment by djarbz** [comment]
I could not reproduce on a new install, I think it was a fluke.

**Comment by penguineer** [comment]
Okay. I'm currently working on an update for the Raspberry Pi part, because Wireguard is now available in the backports.
While I'm at it I'll check if I can add a default behaviour (assuming vanilla Debian) if the tags are not set correctly.
