### ISSUE TITLE
Wireguard dkms on Ubuntu 16.04

### ISSUE THREAD

**Issue by Madic-** [githubixx/ansible-role-wireguard#95]
On ubuntu 16.04 the task **(Ubuntu) Ensure WireGuard DKMS package is removed** removes wireguard and wireguard-dkms.
But the task **(Ubuntu) Install wireguard package** than reinstalls wireguard and wireguard-dkms.

**Comment by githubixx** [comment]
Thanks for reporting! TBH I don't think this is an issue. Before there was a "normal" `wireguard` package, WireGuard was installed from `ppa:wireguard/wireguard` which had a package called `wireguard-dkms`. I added a Molecule test to simulate the issue and there was no difference when it comes to the installed packages. The task `(Ubuntu) Ensure WireGuard DKMS package is removed` was introduced to remove this unneeded package. IMO there is no need to change anything ATM. Does this cause any problems for you currently or was this more an observation maybe?

**Comment by Madic-** [comment]
Everytime when running the role, e.g. when updating unmanaged peers, it recreates the wireguard interface because it first removes the package and then reinstalls it. It's not a big problem. Just disconnects every client at that moment. But maybe it's time for a dist upgrade. The support for Ubuntu Server 16.04 ends April 30th 2021. So for me the issue can be closed
