### ISSUE TITLE
Feature request: add detection for Proxmox kernel

### ISSUE THREAD

**Issue by stevefan1999-personal** [githubixx/ansible-role-wireguard#96]
## Description
It appears the DKMS kernel header detection doesn't account for Proxmox kernel, which although is a parasite of Debian, but have kernel of its own (specifically speaking, Proxmox uses free Debian repos but uses a Ubuntu kernel fork with inclusions of ZFS and Ceph -- weird mix but ok)

## Synopsis
You should see a fatal message in playbook task procedures:
```
TASK [githubixx.ansible_role_wireguard : (Debian) Install kernel headers for the currently running kernel to compile Wireguard with DKMS] ***********************************************************************
fatal: [storage]: FAILED! => {"changed": false, "msg": "No package matching '**linux-headers-5.4.78-2-pve**' is available"}
```
Indeed, `apt install linux-headers-5.4.78-2-pve` doesn't show any positive result, and in fact it should be `pve-headers`.

## Solution
Add the proxmox kernel identifier `pve-headers` to the conditions to check kernel header installation

## Workaround
Skip that specific task when the distribution is Proxmox based, and ensure you manually installed the kernel headers.

## Background
I wished to create my Proxmox cluster in a WireGuard based network fabric over the internet, because it seems you need a LAN IP to make corosync happy.

**Comment by stevefan1999-personal** [comment]
Also, it seems like Proxmox is being really sneaky here -- I can barely find any positive match to know how to figure out Proxmox existence. I searched for the keyword "Proxmox" in `ansible nas -m ansible.builtin.setup | sed '1c {' | jq` and I found only two of such reference which is however for EFI.

These two here are what I will decide to use:
```
        "ansible_kernel": "5.4.78-2-pve",
        "ansible_kernel_version": "#1 SMP PVE 5.4.78-2 (Thu, 03 Dec 2020 14:26:17 +0100)",
```
And I think this might be it, by checking whether we have the substring "pve" in ansible_kernel, it's really murky but I think it will get 90% of the job done (well not to mention the people who liked the kernel of Proxmox but didn't use PVE anyway).

This should also cover Proxmox Backup Server (PBS), as it prefer to use the same kernel fork in Proxmox VE.

**Comment by stevefan1999-personal** [comment]
And what about future Raspberry Pi release that is...both Raspbian and Proxmox? The pace of RPi hardware iteration is incredible as you see with RPi 4 compute modules, and I suspect next year there will even be a Pi hosting industry like [Turing Pi 2](https://turingpi.com/v2/) and a [1U rack for 22 Pi 4s](https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/25#issuecomment-738877163)! This is a lot of compute nodes and I'm sure some of them will be like me running Proxmox and leverage its clustering capability to run massively parallel applications (remember Proxmox isn't just providing VM -- it provides containers as well), or even using k8s and Kata Containers (which does require KVM, or ARM virtualization extension) at the same time. So the possibility of dealing with Proxmox and Raspbian is quite high, should we go ahead to deal with this as well as of right now?

**Comment by githubixx** [comment]
I'll close this for now. Your PR is merged. Further problems can be handled when they pop up.
